apiVersion: tenantoperator.stakater.com/v1beta3
kind: Tenant
metadata:
  name: arsenal
spec:
  owners:
    users:
    - benzema@arsenal.com
  editors:
    users:
    - hakimi@arsenal.com
  viewers:
    users:
    - neymar@arsenal.com
  quota: large
  namespaces:
    withTenantPrefix:
    - build
    - dev
    - prod
    withoutTenantPrefix:
    - user-application-1
    - user-application-2
  onDelete:
    cleanNamespaces: true
    cleanAppProject: true
  sandboxConfig:
    enabled: true
    private: true
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/charts.git'
      - 'https://github.com/DESTINATION_ORG/apps-gitops-config'
      - 'https://nexus-helm-stakater-nexus.ROUTE_SUBDOMAIN/repository/helm-charts/'
    appProject:
      clusterResourceWhitelist:
        - group: tronador.stakater.com
          kind: Environment
      namespaceResourceBlacklist:
        - group: v1
          kind: ConfigMap
