apiVersion: tenantoperator.stakater.com/v1beta3
kind: Tenant
metadata:
  name: arsenal
spec:
  accessControl:
    owners:
      users:
      - benzema@arsenal.com
    editors:
      users:
      - hakimi@arsenal.com
    viewers:
      users:
      - neymar@arsenal.com
  quota: large
  namespaces:
    withTenantPrefix:
    - build
    - dev
    - prod
    withoutTenantPrefix:
    - user-application-1
    - user-application-2

  sandboxConfig:
    enabled: true
    private: true
