apiVersion: tenantoperator.stakater.com/v1beta3
kind: Tenant
metadata:
  name: retail
spec:
  accessControl:
    owners:
      users:
      - bear@nordmart.com
    editors:
      users:
      - wolf@nordmart.com
    viewers:
      users:
      - eagle@nordmart.com
  quota: large
  namespaces:
    sandboxes:
      enabled: true
      private: true
    withTenantPrefix:
    - build
    - dev
    - prod
    withoutTenantPrefix:
    - user-application-1
    - user-application-2

