apiVersion: tenantoperator.stakater.com/v1alpha1
kind: Extensions
metadata:
  name: arsenal
spec:
  tenantName: arsenal
  argoCD:
 
    appProject:
      sourceRepos:
        - 'https://github.com/stakater/charts.git'
        - 'https://github.com/DESTINATION_ORG/apps-gitops-config'
        - 'https://nexus-helm-stakater-nexus.ROUTE_SUBDOMAIN/repository/helm-charts/'
      clusterResourceWhitelist:
        - group: tronador.stakater.com
          kind: Environment
      namespaceResourceBlacklist:
        - group: "v1"
          kind: "ConfigMap"
