apiVersion: tenantoperator.stakater.com/v1alpha1
kind: TemplateGroupInstance
metadata:
  name: git-pat-creds
spec:
  template: git-pat-creds
  selector:
    matchExpressions:
      - key: stakater.com/kind
        operator: In, v
        values: [ build ]
  sync: true