apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-gitops-config
  namespace: rh-openshift-gitops-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd-apps/cluster-name
    repoURL: 'https://github.com/DESTINATION_ORG/apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
