apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-operator-config
  namespace: rh-openshift-gitops-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster-name/tenant-operator-config
    repoURL: 'https://github.com/DESTINATION_ORG/infra-gitops-config.git'
    targetRevision: main
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

