apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webinar-apps-gitops-config
  namespace: rh-openshift-gitops-instance
spec:
  destination:
    namespace: rh-openshift-gitops-instance
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: argocd-apps/CLUSTER_NAME
    repoURL: 'https://github.com/DESTINATION_ORG/webinar-apps-gitops-config'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
